export type ExerciseKind =
  | 'conjugation'
  | 'masdarForm'
  | 'masdarRoot'
  | 'masdarVerb'
  | 'participleForm'
  | 'participleRoot'
  | 'participleVerb'
  | 'verbParticiple'
  | 'verbForm'
  | 'verbMasdar'
  | 'verbPronoun'
  | 'verbRoot'
  | 'rootFormVerb'
  | 'verbTense'
